// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: letters/letters.proto

package letters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LettersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LettersRequest) Reset() {
	*x = LettersRequest{}
	mi := &file_letters_letters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LettersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LettersRequest) ProtoMessage() {}

func (x *LettersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_letters_letters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LettersRequest.ProtoReflect.Descriptor instead.
func (*LettersRequest) Descriptor() ([]byte, []int) {
	return file_letters_letters_proto_rawDescGZIP(), []int{0}
}

type LettersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Letters       []string               `protobuf:"bytes,1,rep,name=letters,proto3" json:"letters,omitempty"`
	Center        string                 `protobuf:"bytes,2,opt,name=center,proto3" json:"center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LettersResponse) Reset() {
	*x = LettersResponse{}
	mi := &file_letters_letters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LettersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LettersResponse) ProtoMessage() {}

func (x *LettersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_letters_letters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LettersResponse.ProtoReflect.Descriptor instead.
func (*LettersResponse) Descriptor() ([]byte, []int) {
	return file_letters_letters_proto_rawDescGZIP(), []int{1}
}

func (x *LettersResponse) GetLetters() []string {
	if x != nil {
		return x.Letters
	}
	return nil
}

func (x *LettersResponse) GetCenter() string {
	if x != nil {
		return x.Center
	}
	return ""
}

var File_letters_letters_proto protoreflect.FileDescriptor

const file_letters_letters_proto_rawDesc = "" +
	"\n" +
	"\x15letters/letters.proto\x12\aletters\"\x10\n" +
	"\x0eLettersRequest\"C\n" +
	"\x0fLettersResponse\x12\x18\n" +
	"\aletters\x18\x01 \x03(\tR\aletters\x12\x16\n" +
	"\x06center\x18\x02 \x01(\tR\x06center2G\n" +
	"\x04Core\x12?\n" +
	"\n" +
	"GetLetters\x12\x17.letters.LettersRequest\x1a\x18.letters.LettersResponseB\fZ\n" +
	"./letters/b\x06proto3"

var (
	file_letters_letters_proto_rawDescOnce sync.Once
	file_letters_letters_proto_rawDescData []byte
)

func file_letters_letters_proto_rawDescGZIP() []byte {
	file_letters_letters_proto_rawDescOnce.Do(func() {
		file_letters_letters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_letters_letters_proto_rawDesc), len(file_letters_letters_proto_rawDesc)))
	})
	return file_letters_letters_proto_rawDescData
}

var file_letters_letters_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_letters_letters_proto_goTypes = []any{
	(*LettersRequest)(nil),  // 0: letters.LettersRequest
	(*LettersResponse)(nil), // 1: letters.LettersResponse
}
var file_letters_letters_proto_depIdxs = []int32{
	0, // 0: letters.Core.GetLetters:input_type -> letters.LettersRequest
	1, // 1: letters.Core.GetLetters:output_type -> letters.LettersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_letters_letters_proto_init() }
func file_letters_letters_proto_init() {
	if File_letters_letters_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_letters_letters_proto_rawDesc), len(file_letters_letters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_letters_letters_proto_goTypes,
		DependencyIndexes: file_letters_letters_proto_depIdxs,
		MessageInfos:      file_letters_letters_proto_msgTypes,
	}.Build()
	File_letters_letters_proto = out.File
	file_letters_letters_proto_goTypes = nil
	file_letters_letters_proto_depIdxs = nil
}
