// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: dictionary.proto

package dict

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordRequest) Reset() {
	*x = WordRequest{}
	mi := &file_dictionary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordRequest) ProtoMessage() {}

func (x *WordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordRequest.ProtoReflect.Descriptor instead.
func (*WordRequest) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *WordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type WordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordResponse) Reset() {
	*x = WordResponse{}
	mi := &file_dictionary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordResponse) ProtoMessage() {}

func (x *WordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordResponse.ProtoReflect.Descriptor instead.
func (*WordResponse) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{1}
}

func (x *WordResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_dictionary_proto protoreflect.FileDescriptor

const file_dictionary_proto_rawDesc = "" +
	"\n" +
	"\x10dictionary.proto\x12\vdicitionary\"!\n" +
	"\vWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"&\n" +
	"\fWordResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2N\n" +
	"\n" +
	"Dictionary\x12@\n" +
	"\tCheckWord\x12\x18.dicitionary.WordRequest\x1a\x19.dicitionary.WordResponseB1Z/github.com/ddd-cmbck/dsp-assigment-1/proto;dictb\x06proto3"

var (
	file_dictionary_proto_rawDescOnce sync.Once
	file_dictionary_proto_rawDescData []byte
)

func file_dictionary_proto_rawDescGZIP() []byte {
	file_dictionary_proto_rawDescOnce.Do(func() {
		file_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionary_proto_rawDesc), len(file_dictionary_proto_rawDesc)))
	})
	return file_dictionary_proto_rawDescData
}

var file_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dictionary_proto_goTypes = []any{
	(*WordRequest)(nil),  // 0: dicitionary.WordRequest
	(*WordResponse)(nil), // 1: dicitionary.WordResponse
}
var file_dictionary_proto_depIdxs = []int32{
	0, // 0: dicitionary.Dictionary.CheckWord:input_type -> dicitionary.WordRequest
	1, // 1: dicitionary.Dictionary.CheckWord:output_type -> dicitionary.WordResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionary_proto_init() }
func file_dictionary_proto_init() {
	if File_dictionary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionary_proto_rawDesc), len(file_dictionary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictionary_proto_goTypes,
		DependencyIndexes: file_dictionary_proto_depIdxs,
		MessageInfos:      file_dictionary_proto_msgTypes,
	}.Build()
	File_dictionary_proto = out.File
	file_dictionary_proto_goTypes = nil
	file_dictionary_proto_depIdxs = nil
}
